/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/totp/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Totp Enroll
         * @description Generate a fresh TOTP secret and return it + a provisioning URI.
         *
         *     The secret is NOT persisted yet. The client must immediately call
         *     POST /api/me/totp/verify with the secret AND a valid code to
         *     commit it.
         */
        post: operations["totp_enroll_api_me_totp_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/totp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Totp Verify
         * @description Commit TOTP enrollment after confirming the user can compute codes.
         */
        post: operations["totp_verify_api_me_totp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Totp Disenroll
         * @description Remove TOTP for the current user. Requires a valid current code.
         */
        delete: operations["totp_disenroll_api_me_totp_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bot Status */
        get: operations["bot_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Config */
        get: operations["read_config_api_config_get"];
        /** Write Config */
        put: operations["write_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/active-asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Active Asset */
        get: operations["read_active_asset_api_active_asset_get"];
        /** Write Active Asset */
        put: operations["write_active_asset_api_active_asset_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Kill
         * @description Request the bot to trip its kill switch.
         *
         *     202 Accepted: the request is queued in Redis; the bot polls and
         *     applies on its next interval (typically within 2 s). Successive
         *     requests are idempotent: a re-poll sees the request even if a
         *     previous one was already consumed.
         */
        post: operations["request_kill_api_kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActiveAssetResponse
         * @description Wire format for the current active asset selection.
         */
        ActiveAssetResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Symbol */
            symbol: string;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
            /** Set By */
            set_by: string;
        };
        /**
         * BotStatusResponse
         * @description High-level snapshot for the dashboard poll endpoint.
         */
        BotStatusResponse: {
            /**
             * Connection State
             * @enum {string}
             */
            connection_state: "connected" | "disconnected" | "unknown";
            /** Kill Switch Tripped */
            kill_switch_tripped: boolean;
            /** Kill Switch Reason */
            kill_switch_reason: string | null;
            open_position: components["schemas"]["OpenPositionResponse"] | null;
            today_pnl: components["schemas"]["PnLResponse"] | null;
        };
        /**
         * ConfigPolicyPayload
         * @description Full runtime configuration the operator can edit from the web app.
         *
         *     `extra="forbid"` rejects unknown keys so a typo in the UI cannot
         *     silently drop a field.
         */
        ConfigPolicyPayload: {
            /** Account Equity Target Usd */
            account_equity_target_usd: number | string;
            /** Max Position Size Usd */
            max_position_size_usd: number | string;
            /** Stop Loss Pct */
            stop_loss_pct: number | string;
            /** Min Profit Per Trade Usd */
            min_profit_per_trade_usd: number | string;
            /** Max Profit Per Trade Usd */
            max_profit_per_trade_usd: number | string;
            /** Min R Multiple */
            min_r_multiple: number | string;
            /** Max Commission Pct Of Target */
            max_commission_pct_of_target: number | string;
            /** Sr Strong Threshold */
            sr_strong_threshold: number;
            /** Sr Weak Threshold */
            sr_weak_threshold: number;
            /** Sr Partial Entry Pct */
            sr_partial_entry_pct: number;
            /** Sr Level Tolerance Pct */
            sr_level_tolerance_pct: number | string;
            /** Sr Lookback Minutes */
            sr_lookback_minutes: number;
            sr_strength_weights: components["schemas"]["SRStrengthWeights"];
            /** Max Daily Loss Usd */
            max_daily_loss_usd: number | string;
            /** Max Trades Per Day */
            max_trades_per_day: number;
            /** Max Orders Per Minute */
            max_orders_per_minute: number;
            /** Min Spread Bps */
            min_spread_bps: number;
            /** Max Spread Bps */
            max_spread_bps: number;
            /** Forbidden Tickers */
            forbidden_tickers?: string[];
            /** Earnings Blackout */
            earnings_blackout: boolean;
            /** Halt Resume Cooldown Seconds */
            halt_resume_cooldown_seconds: number;
            /** No New Entries Before Close Minutes */
            no_new_entries_before_close_minutes: number;
            /** Force Flatten Before Close Minutes */
            force_flatten_before_close_minutes: number;
            /** Consecutive Losses Limit */
            consecutive_losses_limit: number;
            /** Drawdown Pct From Open */
            drawdown_pct_from_open: number | string;
            /** Entry Limit Cancel Seconds */
            entry_limit_cancel_seconds: number;
            /** Config Reload Seconds */
            config_reload_seconds: number;
        };
        /**
         * ConfigPolicyResponse
         * @description Wire format for a single policy version.
         */
        ConfigPolicyResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Created By */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * KillRequest
         * @description Body for POST /api/kill.
         */
        KillRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Totp Code */
            totp_code?: string | null;
        };
        /** OpenPositionResponse */
        OpenPositionResponse: {
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /** Qty */
            qty: string;
            /** Avg Entry Price */
            avg_entry_price: string;
            /** State */
            state: string;
        };
        /** PnLResponse */
        PnLResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Gross Pnl */
            gross_pnl: string;
            /** Commissions */
            commissions: string;
            /** Net Pnl */
            net_pnl: string;
            /** N Trades */
            n_trades: number;
            /** N Wins */
            n_wins: number;
            /** N Losses */
            n_losses: number;
        };
        /**
         * SRStrengthWeights
         * @description Weights for the five components of the S/R strength score.
         */
        SRStrengthWeights: {
            /** Clean Touches */
            clean_touches: number | string;
            /** Volume At Price */
            volume_at_price: number | string;
            /** Ma Confluence */
            ma_confluence: number | string;
            /** Persistence */
            persistence: number | string;
            /** Rejection Quality */
            rejection_quality: number | string;
        };
        /**
         * SetActiveAssetRequest
         * @description Body for PUT /api/active-asset.
         */
        SetActiveAssetRequest: {
            /**
             * Symbol
             * @description US ticker symbol, e.g. AAPL, MSFT, BRK.B.
             */
            symbol: string;
        };
        /** TOTPDisenrollRequest */
        TOTPDisenrollRequest: {
            /** Code */
            code: string;
        };
        /** TOTPEnrollResponse */
        TOTPEnrollResponse: {
            /** Secret */
            secret: string;
            /** Provisioning Uri */
            provisioning_uri: string;
        };
        /** TOTPVerifyRequest */
        TOTPVerifyRequest: {
            /** Secret */
            secret: string;
            /** Code */
            code: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Totp Enrolled
             * @default false
             */
            totp_enrolled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    totp_enroll_api_me_totp_enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TOTPEnrollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    totp_verify_api_me_totp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    totp_disenroll_api_me_totp_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPDisenrollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bot_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigPolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPolicyPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigPolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_active_asset_api_active_asset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveAssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_active_asset_api_active_asset_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetActiveAssetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveAssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_kill_api_kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tradingbot_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
